BEGIN
  DECLARE CONTINUE HANDLER FOR SQLSTATE '42710' BEGIN END;
  CREATE TABLE BENOIT_DB2 (
    ID   INTEGER AS IDENTITY,
    NAME VARCHAR(50),
    PRIMARY KEY (ID)
  );

END
  GO
-- drop table BENOIT_DB2;
